---
title: "It's A Hit: Tony Award-Winning Broadway Shows"
author: "Madeleine Snow"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(rvest)

```

```{r data, include=FALSE}

# I scraped the Wikipedia page for the Tony Award for Best Musical with rvest. I inspected the table elements, separated by decade, individually on the webpage and copied the XPath for each. I specified the url so that I could inspect the HTML structure. 

# I wanted to return a data frame, so I piped in html_node() with the XPath for the first table, the 1940s, piping in another command to get a table output. After looking at the table, I wanted to get rid of rows filled with NA, so I used na.omit(). 

# I repeated this process for all of the decades, but as I got to the 2000s and 2010s, I received errors reading in the code, so I need to revisit these decades for the most complete picture of the winners of and nominees for Best Musical.

# I used rbind() to combine all of the tables for each decade into a single data frame. I noticed that year and awards ceremony number were in one column, so I used the separate function to make them into 2 columns.

# Scraping the code in this way did not denote which shows actually won the awards, which are denoted through a blue-colored fill on Wikipedia. I manually created a column in each decade table with a dummy variable to distinguish winners versus nominees.

# I was interested in looking at which shows had a female writer on the writing team as a book writer, lyricist, and/or composer. I created another dummy variable to denote which shows had at least one female writer versus no female writers.

# I hope to scrape data similarly and create the same dummy variables from the Wikipedia page for the Tony Award for Best Play. I would like to create a for-loop or function that would simplify my code and therefore reduce possible errors.

url <- 'https://en.wikipedia.org/wiki/Tony_Award_for_Best_Musical'
url <- read_html('https://en.wikipedia.org/wiki/Tony_Award_for_Best_Musical')

bm40s <- url %>% 
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[2]') %>% 
  html_table(fill = TRUE) %>% 
  na.omit()

bm40s$Winner <- c(1)
bm40s$Women <- c(1)
bm40s$Decade <- c("1940s")

bm50s <- url %>% 
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[3]') %>% 
  html_table(fill = TRUE) %>% 
  na.omit()
bm50s$Decade <- c("1950s")


bm50s$Winner <- c(1,1,1,1,1,1,1,0,1,0,0,0,1,0,0,0,0,1,0,0)
bm50s$Women <- c(0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0)

bm60s <- url %>% 
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[4]') %>% 
  html_table(fill = TRUE) %>% 
  na.omit()

bm60s$Winner <- c(1,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0)
bm60s$Women <- c(0,0,0,1, #1960
                 0,1,0,0, #1961
                 0,1,0,0, #1962
                 0,0,0,0, #1963
                 0,1,0,0, #1964
                 0,0,1,1, #1965
                 0,0,0,1, #1966
                 0,0,0,1, #1967
                 1,0,1,0, #1968
                 0,0,0,0) #1969
bm60s$Decade <- c("1960s")

bm70s <- url %>% 
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[5]') %>% 
  html_table(fill = TRUE) %>% 
  na.omit()

bm70s$Winner <- c(1,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0)
bm70s$Women <- c(1,0,0, #1970
                 0,0,0, #1971
                 0,0,0,0, #1972
                 0,1,0,0, #1973
                 1,0,1, #1974
                 0,0,1,0, #1975
                 0,0,0,0, #1976
                 0,1,0,0, #1977
                 0,0,1,1, #1978
                 0,1,1,1) #1979
bm70s$Decade <- c("1970s")

bm80s <- url %>% 
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[6]') %>% 
  html_table(fill = TRUE) %>% 
  na.omit()

bm80s$Winner <- c(1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0)
bm80s$Women <- c(0,0,0,1, #1980
                 0,0,0,0, #1981
                 0,0,0,1, #1982
                 0,0,0,0, #1983
                 0,1,0,0, #1984
                 0,1,1,1, #1985
                 0,0,0,0, #1986
                 0,0,0,0, #1987
                 0,0,0,0, #1988
                 0,0,0) #1989
bm80s$Decade <- c("1980s")

bm90s <- url %>% 
  html_node(xpath = '//*[@id="mw-content-text"]/div/table[7]') %>% 
  html_table(fill = TRUE) %>% 
  na.omit()

bm90s$Winner <- c(1,0,0,0,
                  1,0,0,0, 
                  1,0,0,0,
                  1,0,0,0,
                  1,0,0,0,
                  1,0, #1995
                  1,0,0,0,
                  1,0,0,0,
                  1,0,0,0,
                  1,0,0,0)

bm90s$Women <- c(0,0,0,0, #1990
                 1,0,1,1, #1991
                 0,0,0,1, #1992
                 0,0,0,0, #1993
                 0,0,1,0, #1994
                 0,0, #1995
                 0,1,1,0, #1996
                 0,1,0,0, #1997
                 1,0,1,1, #1998
                 0,0,1,0) #1999
bm90s$Decade <- c("1990s")

bm_all <- rbind(bm40s, bm50s, bm60s, bm70s, bm80s, bm90s) %>% 
  separate(Year, into = c('Year', 'Ceremony'), sep = 4) %>%
  arrange(Year)

```

```{r graphic, include=TRUE}

# For my graphic, I wanted the dummy variables for nominee vs winner and 0 vs >1 female writers to be distinct and clear, so I renamed them appropriately.

# I knew that I wanted to show the distinction between absence vs presence on winning vs nominated writing teams for the Tony Award for Best Musical, so I set the x axis to show nominated versus winning writing teams (1 count = 1 show = 1 writing team) 

# I knew that a singular graphic would appear cluttered, so I decided to facet by decade, so I went into the code above and created a Decade column in each respective decade table. 

# I wanted faceted bar graphs to show the relative number of writing teams with and without a female writer, so to show the respective counts, I tried geom_bar with position set equal to "dodge."

# I noticed that the zero count of >1 female writer for some nominated and winning categories was dropped in some faceted plots. I wanted to make the zero count clear, so I used a line of code which I found on an online forum, the preserve = "single" command within the dodge position in geom_bar, to fix this.

# Finally, in keeping with a good graphic, I added an axis label, title, subtitle, and legend title in labs().

bm_all$Winner[bm_all$Winner==0] <- "Nominee"
bm_all$Winner[bm_all$Winner==1] <- "Winner"

bm_all$Women[bm_all$Women==0] <- "No Female Writers"
bm_all$Women[bm_all$Women==1] <- "At Least 1 Female Writer"

ggplot(bm_all, aes(x = Winner, fill = Women)) +
  geom_bar(position = position_dodge(preserve = "single")) +
  facet_wrap(. ~ Decade) +
  labs(x = "Tony Award Nominees/Winners",
       fill = "Writing Teams' Gender Composition",
       title = "Gender of Broadway Writers",
       subtitle = "Shows up for Tony Award for Best Musical, 1949-1999",
       caption = "*Writing teams are comprised of book writers, lyricists, and/or composers*")

```
